applications/admin_exonica/urls.py
from django.urls import path

from . import views


app_name = "app_admin"

urlpatterns = [
    path(
        'categoria-crear/', 
        views.CategoriaArticulosCreateView.as_view(), 
        name='categoria_crear'
    ),
    path(
        'articulos-crear/', 
        views.ArticulosCreateView.as_view(), 
        name='articulos_crear'
    ),
    path(
        'articulos-lista/', 
        views.listarArticulosListView.as_view(), 
        name='articulos_listar'
    ),
    path(
        'categoria-lista/', 
        views.listarCategoriasListView.as_view(), 
        name='categoria_listar'
    ),
    path(
        'payments-lista/', 
        views.listarPayments.as_view(), 
        name='payments_listar'
    ),
    path(
        'categoria-eliminar/<pk>/', 
        views.CategoriaDeleteView.as_view(), 
        name='categoria_eliminar'
    ),
    path(
        'categoria-editar/<pk>/', 
        views.CategoriaUpdateView.as_view(), 
        name='categoria_editar'
    ),
    path(
        'articulo-eliminar/<pk>/', 
        views.ArticulosDeleteView.as_view(), 
        name='articulo_eliminar'
    ),
    path(
        'articulo-editar/<pk>/', 
        views.ArticulosUpdateView.as_view(), 
        name='articulo_editar'
    ),
    path(
        'anuncios-crear/', 
        views.AnunciosCreateView.as_view(), 
        name='anuncios'
    ),
    path(
        'anuncios-listar/', 
        views.listarAnunciosListView.as_view(), 
        name='anuncios_listar'
    ),
    path(
        'anuncios-editar/<pk>/', 
        views.AnuncioUpdateView.as_view(), 
        name='anuncios_editar'
    ),
      path(
        'anuncios-eliminar/<pk>/', 
        views.AnunciosDeleteView.as_view(), 
        name='anuncios_eliminar'
    ),
    path(
        'mensajes-lista/', 
        views.listarMensjaesListView.as_view(), 
        name='mensajes_listar'
    ),
    path(
        'mensaje-ver/<pk>/', 
        views.MensajeDetailView.as_view(), 
        name='mensaje_ver'
    ),
    path(
        'procesar-msj/<pk>/', 
        views.procesarMsjView.as_view(), 
        name='procesar_msj'
    ),
    path(
        'mensaje-eliminar/<pk>/', 
        views.MensajeDeleteView.as_view(), 
        name='mensaje_eliminar'
    ),
    path(
        'editar-payment/<pk>/', 
        views.DatosPaymentUpdateView.as_view(), 
        name='editar_payment'
    ),
    path(
        'delete-payment/<pk>/', 
        views.PaymentDeleteView.as_view(), 
        name='delete_payment'
    ),
    path(
        'about-exo/', 
        views.quienSomosView.as_view(), 
        name='about_exo'
    ),
    path(
        'editar-about-exo/<pk>/', 
        views.quienesSomosUpdateView.as_view(), 
        name='editar_about_exo'
    ),
]

applications/store_exonica/urls.py
from django.urls import path
from . import views

app_name = "store_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(), 
        name='pub_articulos'
    ),
    path(
        'inform-contact', 
        views.ContactPageView.as_view(), 
        name='inform_contact'
    ),
    path(
        'about-exo', 
        views.aboutExonica.as_view(), 
        name='about_exo'
    ),
    path(
        'articulo-pub/<slug>/', 
        views.ArticulosDetailView.as_view(), 
        name='articulo_pub'
    ),
    path(
        'articulo-categoria/', 
        views.ArticulosPorCategorias.as_view(), 
        name='articulo_categoria'
    ),
    path(
        'mensaje-contacto/', 
        views.MensajeCreateView.as_view(), 
        name='mensaje_contacto'
    ),
    path(
        'car-shop/', 
        views.CarPageView.as_view(), 
        name='car_shop'
    ),
    path(
        'add-car-shop/<pk>/', 
        views.AddCarView.as_view(), 
        name='add_car_shop'
    ),
    path(
        'api/num-car/', 
        views.CarNumApiView.as_view(),
    ),
    path(
        'eliminar-producto/<pk>/', 
        views.CarDeleteView.as_view(), 
        name='eliminar_producto'
    ),
    path(
        'eliminar-todo', 
        views.CarDeleteViewAll.as_view(), 
        name='eliminar_todo'
    ),
    path(
        'payment-paypal/', 
        views.PaymentView.as_view(), 
        name='payment_paypal'
    ),
    path(
        'payment-trans/', 
        views.PaymentViewTrans.as_view(), 
        name='payment_trans'
    ),
    path(
        'confirm-order/', 
        views.confirmOrderView.as_view(), 
        name='confirm_order'
    ),
    path(
        'gracias-por-comprar/', 
        views.GraciasPorComprarView.as_view(), 
        name='gracias_comprar'
    ),
    path(
        'historial-compras/', 
        views.historialComprasView.as_view(), 
        name='historial_compras'
    ),
    path(
        'rest-car/<pk>/', 
        views.CarShopUpdateViewRest.as_view(), 
        name='rest_car'
    ),
    path(
        'sum-car/<pk>/', 
        views.CarShopUpdateViewMas.as_view(), 
        name='sum_car'
    ),
]

applications/users/urls.py
from django.urls import path

from . import views

app_name = "user_app"

urlpatterns = [
    path(
        'userRegister', 
        views.UserRegisterView.as_view(), 
        name='Register'
    ),
    path(
        'userList', 
        views.UserListView.as_view(), 
        name='userList'
    ),
    path(
        'userEdit/<pk>/', 
        views.UserUpdateView.as_view(), 
        name='userEdit'
    ),
      path(
        'usuario-eliminar/<pk>/', 
        views.UserDeleteView.as_view(), 
        name='usuario_eliminar'
    ),
    path(
        'userLogin', 
        views.loginUser.as_view(), 
        name='login'
    ),
    path(
        'userLogout', 
        views.logoutUser.as_view(), 
        name='logout'
    ),
    path(
        'perfil-usuario', 
        views.UserPerfil.as_view(), 
        name='perfil_usuario'
    ),
    path(
        'editar-perfil-usuario', 
        views.UserUpdateForUser.as_view(), 
        name='editar_perfil_usuario'
    ),
]

exonica_online/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.store_exonica.sitemap import (
    Sitemap,
    articulosSitem
)
urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.admin_exonica.urls')),
    re_path('', include('applications.store_exonica.urls')),
    re_path('', include('applications.users.urls')),
    # Url Ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site':Sitemap(
        [
            'store_app:pub_articulos'
        ]
    ),
    'articulos': articulosSitem
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml',
        sitemap, 
        {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]


urlpatterns = urlpatterns_main + urlpatterns_sitemap

templates/includes/admin_lateral.html
{% load static %}

    {% if user.is_authenticated %}
    <div class="nav__items container__admin">
        <ul class="list">

            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/store.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'store_app:pub_articulos' %}" class="nav__link">Inicio</a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/info-circle.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'app_admin:about_exo' %}" class="nav__link">Información</a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/category-alt.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'app_admin:categoria_listar' %}" class="nav__link">Categorias</a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/user-check.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'user_app:userList' %}" class="nav__link">Usuarios</a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/cart.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'app_admin:articulos_listar' %}" class="nav__link">Articulos</a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/rectangle.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'app_admin:anuncios_listar' %}" class="nav__link">Anuncios</a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/chat.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'app_admin:mensajes_listar' %}" class="nav__link">
                        Mensajes
                        {% if msjnoread %}
                            ({{msjnoread}}) 
                        {% endif %}
                    </a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/heart.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'app_admin:payments_listar' %}" class="nav__link">
                        Ventas
                        {% if comprasnum %}
                            ({{comprasnum}}) 
                        {% endif %}
                    </a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/user-adm.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'user_app:perfil_usuario' %}" class="nav__link nav__link_admin">Perfil de usuario</a>
                </div>
            </li>
            <li class="list__item backhover">
                <div class="list__button">
                    <img src="{% static 'img/log-out.svg' %}" class="list__img icon_adm">
                    <a href="{% url 'user_app:logout' %}" class="nav__link">Cerrar sesión</a>
                </div>
            </li>
        </ul>
    </div>
    {% endif %}

templates/includes/footer.html
{% load static %}
<footer class="footer">
    <div class="footer__container">
        
        {% if user.is_authenticated %}
        <a class="footer__link_login" href="{% url 'user_app:perfil_usuario' %}">
            Mi perfil
        </a>
        {% else %}
        <a class="footer__link_login" href="{% url 'user_app:login' %}">
            Iniciar sesión
        </a>
        {% endif %} 
        <a class="footer__link_about" href="{% url 'store_app:about_exo' %}">
            Sobre nosotros
        </a>
    </div>

    <div class="footer__container">
        <h2 class="footer__text">Nuestras redes sociales:</h2>
            <a class="footer__link2" href="https://www.facebook.com/derlyebander">
                <img class="picture__fb" src="{% static 'img/facebook.png' %}" alt="">
            </a>
            <a class="footer__link2" href="https://web.whatsapp.com/">
                <img class="picture__whats" src="{% static 'img/whatsapp.png' %}" alt="">
            </a>
        </div>
    </div>

    <div class="footer__container footer__container--envios">
        <h2 class="footer__text">Envios por:</h2>
            <img class="picture__estafeta" src="{% static 'img/estafeta.png' %}" alt="">
            <br>
            <img class="picture__dhl" src="{% static 'img/dhl.png' %}" alt="">
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}
<header class="hero">
    <nav class="nav">
        <section class="nav__container container">
            <figure class="nav__logo">
                <img src="{% static 'img/exologow.png' %}" class="nav__logo_img" alt="">
            </figure>
            <div id="num_car" class="nav__links">
                <a class="nav__astyle nav__astyle_header {% if request.resolver_match.url_name == 'pub_articulos' %}active{% endif %}" href="{% url 'store_app:pub_articulos' %}">
                    <img class="nav__img" src="{% static 'img/home.png' %}"> 
                    <p>INICIO</p>
                </a>
                <a class="nav__astyle nav__astyle_header {% if request.resolver_match.url_name == 'articulo_categoria' %}active{% endif %}" href="{% url 'store_app:articulo_categoria' %}"><img class="nav__img1" src="{% static 'img/category.png' %}"> <p>CATEGORIAS</p></a>
                
                {% if request.resolver_match.url_name == 'pub_articulos' %}
                <a class="nav__astyle nav__astyle_header" href="#aboutus"><img class="nav__img2" src="{% static 'img/store.png' %}"> <p>SOBRE NOSOTROS</p></a>
                {% else %}
                <a class="nav__astyle nav__astyle_header {% if request.resolver_match.url_name == 'about_exo' %}active{% endif %}" href="{% url 'store_app:about_exo' %}"><img class="nav__img2" src="{% static 'img/store.png' %}"> <p>SOBRE NOSOTROS</p></a>
                {% endif %}
                
                <a class="nav__astyle nav__astyle_header {% if request.resolver_match.url_name == 'inform_contact' %}active{% endif %}" href="{% url 'store_app:inform_contact' %}"><img class="nav__img3" src="{% static 'img/support.png' %}"> <p>Contactanos</p></a>
                <a class="nav__astyle nav__astyle_cart" href="{% url 'store_app:car_shop' %}"><img class="nav__img4 nav__picture" src="{% static 'img/cart.png' %}"><h5 class="nav__num" v-show="nc">{$ nc.total $}</h5></a>
            </div>
        </section>

        <section class="nav__container_rigth container">
            <label for="check" class="nav__astyle2"></label>
            <div class="nav__items">
                <ul class="list">
                    <li class="list__item">
                        <div class="list__button">
                            <img src="{% static 'img/dashboard.png' %}" class="list__img">
                            <a href="{% url 'store_app:pub_articulos' %}" class="nav__link">Inicio</a>
                        </div>
                    </li>
                    <li class="list__item list__item--click list__item_lateral">
                        <div class="list__button list__button--click">
                            <img src="{% static 'img/store_left.png' %}" class="list__img">
                            <a href="#" class="nav__link">Tienda</a>
                            <img src="{% static 'img/arrow.svg' %}" class="list__arrow">
                        </div>
                        <ul class="list__show">
                            <li class="list__inside">
                                <a class="nav__link nav__link--inside" href="{% url 'store_app:articulo_categoria' %}">CATEGORIAS</a>
                            </li>
                            <li class="list__inside">
                                {% if request.resolver_match.url_name == 'pub_articulos' %}
                                <a class="nav__link nav__link--inside" href="#aboutus">SOBRE NOSOTROS</a>
                                {% else %}
                                <a class="nav__link nav__link--inside" href="{% url 'store_app:about_exo' %}">SOBRE NOSOTROS</a>
                                {% endif %}
                            </li>
                            <li class="list__inside">
                                <a class="nav__link nav__link--inside" href="{% url 'store_app:inform_contact' %}">Contactanos</a>
                            </li>
                        </ul>
                    </li>

                {% if user.is_authenticated %}
                {% if user.ocupations == 'Administrador' %}
                    <li class="list__item list__item--click ">
                        <div class="list__button list__button--click">
                            <img src="{% static 'img/dialpad.png' %}" class="list__img">
                            <a href="#" class="nav__link">Administración</a>
                            <img src="{% static 'img/arrow.svg' %}" class="list__arrow">
                        </div>
                        <ul class="list__show">
                            <li class="list__inside">
                                <a href="{% url 'app_admin:mensajes_listar' %}" class="nav__link nav__link--inside">
                                    Mensajes
                                    {% if msjnoread %}
                                       ({{msjnoread}}) 
                                    {% endif %}</a>
                            </li>
                            <li class="list__inside">
                                <a href="{% url 'app_admin:payments_listar' %}" class="nav__link nav__link--inside">
                                    Compras
                                    {% if comprasnum %}
                                        ({{comprasnum}}) 
                                    {% endif %}
                                </a>
                            </li>
                        </ul>
                    </li>
                    {% endif %}
                    <li class="list__item list__item--click">
                        <div class="list__button list__button--click">
                            <img src="{% static 'img/user-circle.png' %}" class="list__img">
                            <a href="#" class="nav__link">Mi perfil</a>
                            <img src="{% static 'img/arrow.svg' %}" class="list__arrow">
                        </div>
                        <ul class="list__show">
                            <li class="list__inside">
                                <a href="{% url 'store_app:historial_compras' %}" class="nav__link nav__link--inside">
                                    Mis ultimas compras
                                </a>
                            </li>
                            <li class="list__inside">
                                <a href="{% url 'user_app:perfil_usuario' %}" class="nav__link nav__link--inside">
                                    Perfil de {{user.nombre}}
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="list__item">
                        <div class="list__button">
                            <img src="{% static 'img/log-out-solid.png' %}" class="list__img">
                            <a href="{% url 'user_app:logout' %}" class="nav__link">Cerrar sesión</a>
                        </div>
                    </li>

                {% else %}
                    <li class="list__item">
                        <div class="list__button">
                            <img src="{% static 'img/log-in.png' %}" class="list__img">
                            <a href="{% url 'user_app:login' %}" class="nav__link">Iniciar sesión</a>
                        </div>
                    </li>
                    <li class="list__item">
                        <div class="list__button">
                            <img src="{% static 'img/user-plus.png' %}" class="list__img">
                            <a href="{% url 'user_app:Register' %}" class="nav__link">Registrarse</a>
                        </div>
                    </li>
                {% endif %}

                </ul>
            </div>
        </section>
    </nav>
</header>