applications/store_exonica/urls.py
from django.urls import path
from . import views

app_name = "store_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(), 
        name='pub_articulos'
    ),
    path(
        'inform-contact', 
        views.ContactPageView.as_view(), 
        name='inform_contact'
    ),
    path(
        'about-exo', 
        views.aboutExonica.as_view(), 
        name='about_exo'
    ),
    path(
        'articulo-pub/<slug>/', 
        views.ArticulosDetailView.as_view(), 
        name='articulo_pub'
    ),
    path(
        'articulo-categoria/', 
        views.ArticulosPorCategorias.as_view(), 
        name='articulo_categoria'
    ),
    path(
        'mensaje-contacto/', 
        views.MensajeCreateView.as_view(), 
        name='mensaje_contacto'
    ),
    path(
        'car-shop/', 
        views.CarPageView.as_view(), 
        name='car_shop'
    ),
    path(
        'add-car-shop/<pk>/', 
        views.AddCarView.as_view(), 
        name='add_car_shop'
    ),
    path(
        'api/num-car/', 
        views.CarNumApiView.as_view(),
    ),
    path(
        'eliminar-producto/<pk>/', 
        views.CarDeleteView.as_view(), 
        name='eliminar_producto'
    ),
    path(
        'eliminar-todo', 
        views.CarDeleteViewAll.as_view(), 
        name='eliminar_todo'
    ),
    path(
        'payment-paypal/', 
        views.PaymentView.as_view(), 
        name='payment_paypal'
    ),
    path(
        'payment-trans/', 
        views.PaymentViewTrans.as_view(), 
        name='payment_trans'
    ),
    path(
        'confirm-order/', 
        views.confirmOrderView.as_view(), 
        name='confirm_order'
    ),
    path(
        'gracias-por-comprar/', 
        views.GraciasPorComprarView.as_view(), 
        name='gracias_comprar'
    ),
    path(
        'historial-compras/', 
        views.historialComprasView.as_view(), 
        name='historial_compras'
    ),
    path(
        'rest-car/<pk>/', 
        views.CarShopUpdateViewRest.as_view(), 
        name='rest_car'
    ),
    path(
        'sum-car/<pk>/', 
        views.CarShopUpdateViewMas.as_view(), 
        name='sum_car'
    ),
]

exonica_online/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.store_exonica.sitemap import (
    Sitemap,
    articulosSitem
)
urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.admin_exonica.urls')),
    re_path('', include('applications.store_exonica.urls')),
    re_path('', include('applications.users.urls')),
    # Url Ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site':Sitemap(
        [
            'store_app:pub_articulos'
        ]
    ),
    'articulos': articulosSitem
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml',
        sitemap, 
        {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]


urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/store_exonica/models.py
from django.db import models
from django.db.models.fields import BooleanField
from applications.admin_exonica.managers import ContactManager, PaymentManager
from applications.admin_exonica.models import Articulos
from .managers import CarShopManager
from django.conf import settings
from django.db.models.signals import post_save
from PIL import Image
# app_terceros
from model_utils.models import TimeStampedModel

class FormContact(TimeStampedModel):
    """Formulario de contacto"""
    full_name = models.CharField(
        'Nombres', 
        max_length=60
    )
    email = models.EmailField()
    celphone= models.CharField(
        'Celular',
        blank=True,
        max_length=10
    )
    message = models.TextField(
        'Mensaje',
        max_length=200
    )
    read = models.BooleanField(default=False)

    objects = ContactManager()

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Mensajes'

    def __str__(self):
        return self.full_name

class CarShop(TimeStampedModel):
    """Modelo que representa a un carrito de compras"""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='user_carshop',
        on_delete=models.CASCADE,
    )

    product = models.ForeignKey(
        Articulos,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_car'
    )
    subtotal = models.DecimalField(
        'Subtotal', 
        max_digits=10, 
        decimal_places=2,
    )
    instalacion = models.BooleanField()
    count = models.PositiveIntegerField('Cantidad')
    
    objects = CarShopManager()

    class Meta:
        verbose_name = 'Carrito de compras'
        verbose_name_plural = 'Carrito de compras'
        ordering = ['-created']

    def __str__(self):
        return str(self.product.title)

class Payment(TimeStampedModel):
    VERYFY = 'VERIFICANDO DATOS'
    ORDERED = 'EN PROCESO DE ENVIO'
    SHIPPED = 'EN CAMINO'
    ARRIVED = 'ENTREGADO'

    PAYPAL = 'PayPal'
    TRANSFERENCIA = 'Transferencia'

    STATUS_CHOICES = (
        (VERYFY, 'VERIFICANDO DATOS'),
        (ORDERED, 'EN PROCESO DE ENVIO'),
        (SHIPPED, 'EN CAMINO'),
        (ARRIVED, 'ENTREGADO')
    )
    STATUS_CHOICES2 = (
        (PAYPAL, 'PayPal'),
        (TRANSFERENCIA, 'Transferencia'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='user_payment',
        on_delete=models.CASCADE,
    )
    payment_method = models.CharField(max_length=20, choices=STATUS_CHOICES2)
    comprobante_pago = models.ImageField(
        'Comprobante de pago',
        upload_to='comprobantes_de_pago',
        height_field=None,
        width_field=None,
        max_length=None,
        null=True
    )
    amount = models.FloatField()
    succesful = BooleanField()
    raw_response = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    
    objects = PaymentManager()

    class Meta:
        verbose_name = 'Payment'
        ordering = ['-created']


    def delete(self, *args, **kwargs):
        if self.payment_method == 'Transferencia':
            # recuras la ruta del archivo en el disco
            storage, path = self.comprobante_pago.storage, self.comprobante_pago.path
            # se ejecuta el metodo delete del modelo
            super(Payment, self).delete(*args, **kwargs)
            # una vez eliminado limpias el archivo de disco
            storage.delete(path)
        else:
            super(Payment, self).delete(*args, **kwargs)

def optimize_image(sender, instance, **kwargs):
    print("------------------------")
    if instance.comprobante_pago:
        comprobante_pago = Image.open(instance.comprobante_pago.path)
        comprobante_pago.save(instance.comprobante_pago.path, quality=70, optimize=True)

post_save.connect(optimize_image, sender=Payment)


class PaymentDetail(TimeStampedModel):
    """Modelo que representa a una venta en detalle"""

    product = models.ForeignKey(
        Articulos,
        on_delete=models.CASCADE,
        verbose_name='producto',
        related_name='product_sale'
    )
    sale = models.ForeignKey(
        Payment,
        on_delete=models.CASCADE, 
        related_name='detail_payment'
    )
    count = models.PositiveIntegerField('Cantidad')
    price_sale = models.DecimalField(
        'Precio Venta', 
        max_digits=10, 
        decimal_places=2
    )
    instalacion = models.BooleanField()
    costo_instalacion = models.DecimalField(
        'Instalación', 
        max_digits=10, 
        decimal_places=2,
    )
    #

    objects = CarShopManager()

    class Meta:
        verbose_name = 'Producto Vendido'
        verbose_name_plural = 'Productos vendidos'

    def __str__(self):
        return str(self.sale.id) + ' - ' + str(self.product.title)


class AboutExonica(TimeStampedModel):
    """modelo para datos en pantalla home"""
    qsomos = models.TextField(
        'Quienes somos', 
        max_length=500
    )

applications/store_exonica/forms.py
from django import forms
from .models import FormContact, Payment


class Form_contact(forms.ModelForm):

    class Meta:
        
        model = FormContact
        fields = (
            'full_name',
            'email',
            'celphone',
            'message',
        )
        widgets = {
            'full_name': forms.TextInput(
                attrs= {
                    'placeholder': 'Escribe tu nombre completo',
                    'class': 'form__two',
                }
            ),
            'email': forms.EmailInput(
                attrs= {
                    'placeholder': 'usuario@email.com',
                    'class': 'form__two',
                }
            ),
            'celphone': forms.TextInput(
                attrs= {
                    'placeholder': '555-555-5555',
                    'class': 'form__two',
                }
            ),
            'message': forms.Textarea(
                attrs= {
                    'placeholder': 'Escribe tu mensaje',
                    'class': 'form__two form__two--textarea',
                }
            ),
            
        }


class VentaForm(forms.Form):
    count = forms.IntegerField(
        label='Cantidad',
        min_value=1,
        widget=forms.NumberInput(
            attrs = {
                'value': '1',
                'class': 'uk-input',
            }
        )
    )
    instalacion = forms.BooleanField(
        label='Deseo contratar la instalación',
        required=False,
        widget=forms.CheckboxInput(
            attrs = {
                'class': 'detail__check',
            }
        )
    )

    #
    def clean_count(self):
        count = self.cleaned_data['count']
        if count < 1:
            raise forms.ValidationError('Ingrese una cantidad mayor a cero')

        return count


class Form_payment_trans(forms.ModelForm):
    
    class Meta:
        
        model = Payment
        fields = (
            'comprobante_pago',
        )

templates/store/car-shop.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %} Exonica Soluciones en Tecnología {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="carshop">
    {% if productos %}
        <div class="carshop__container_cab">
                <div class="carshop__mas">
                    <a href="{% url 'store_app:articulo_categoria' %}" type="submit" class="section_new__link--mas"> Ir por mas productos</a> 
                </div>
                <div class="carshop__total">
                    <a href="#modal-pay" class="section_new__link--pay">Pagar ahora</a> 
                    <p class="carshop__text_total">Total: ${{ total_all | floatformat:2 | intcomma }}</p>
                </div>
        </div>
        <table class="carshop__table">
            <thead>
                <tr>
                    <th></th>
                    <th>Producto</th>
                    <th>Precio</th>
                    <th>Descripción</th>
                    <th>Cantidad</th>
                    <th>Instalación</th>
                    <th>Subtotal</th>
                    <th>Quitar</th>
                </tr>
            </thead>
            <tbody>
                
                {% for p in productos %}
                <tr>
                    <td><img src="{{ p.product.imagen.url }}" class="carshop__image_product"> </td>
                    <td><p class="table_name">Producto:</p> {{ p.product.title }}</td>
                    <td><p class="table_name">Precio:</p> ${{ p.product.precio | floatformat:2 | intcomma }}</td>
                    <td>{{ p.product.descripcion|safe }}</td>
                    <td>
                        <form action="{% url 'store_app:rest_car' p.id %}" method="post" class="carshop__form_arit_menos"> {% csrf_token %}
                            <button type="submit" class="section_new__link section_new__link--opacity section_new__link--arit-menos">-</button>
                        </form>
                        
                            <p class="table_name">Cantidad: </p> {{ p.count }}
                        
                        <form action="{% url 'store_app:sum_car' p.id %}" method="post" class="carshop__form_arit_mas"> {% csrf_token %}
                            <button type="submit" class="section_new__link section_new__link--opacity section_new__link--arit">+</button>
                        </form>
                    </td>
                        {% if p.instalacion == True %}
                            {% if p.user.estado == 'Sonora' %}
                            <td><p class="table_name">Instalación:</p> ${{p.product.precio_inst | floatformat:2 | intcomma}}</td>
                            {% else %}
                            <td><p class="table_name">Instalación:</p> ${{p.product.precio_inst_fuera | floatformat:2 | intcomma}}</td>
                            {% endif %}
                        {% else %}
                        <td><p class="table_name">Instalación:</p> No solicitada</td>
                        {% endif %}
                    <td><p class="table_name">Subtotal:</p> ${{ p.subtotal }}</td>
                    <td>
                        <form action="{% url 'store_app:eliminar_producto' p.id %}" method="post"> {% csrf_token %}
                            <button class="carshop__btn_delete" type="submit">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24" style="fill: rgba(255, 248, 248, 1);"><path d="M5 20a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8h2V6h-4V4a2 2 0 0 0-2-2H9a2 2 0 0 0-2 2v2H3v2h2zM9 4h6v2H9zM8 8h9v12H7V8z"></path><path d="M9 10h2v8H9zm4 0h2v8h-2z"></path></svg>
                            </button> 
                        </form>
                    </td>
                </tr>
                {% endfor %}
                    
                
            </tbody>
        </table>
        <div>
            <form class="carshop__form_delete_all" action="{% url 'store_app:eliminar_todo' %}" method="post">{% csrf_token %}
                <button type="submit" class="carshop__delete_all">Limpiar todo</button> 
            </form>
            
        </div>
    {% else %}
        <div class="carshop__none-product">
            <h1 class="carshop__none_text">Tu carrito esta vacio</h1>
            <img class="carshop__none_img" src="{% static 'img/cart-none.svg' %}" alt="">
        </div>
    {% endif %}
        
    

    <div id="modal-pay" class="payments">
        <div class="payments__container">
            <a href="#" class="payments__close">X</a>
            <h2 class="payments__title">Elige un metodo de pago</h2>
                <img class="carshop__img_trans" src="{% static 'img/payments-transfer.svg' %}" alt="">
                <a class="payments__link--trans" href="{% url 'store_app:payment_trans' %}">    
                    <p>Hacer deposito o transferencia</p>
                </a>
                <img class="carshop__img_card" src="{% static 'img/payments-card.svg' %}" alt="">
                <a class="payments__link--card" href="{% url 'store_app:payment_paypal' %}">
                    <p>Pagar con tarjeta</p>
                </a>
        </div>
    </div>

        
    <div class="paginated__admin">
        {% if is_paginated %}
        <ul>
            {% if page_obj.has_previous %}
                <li><a href="?page={{page_obj.previous_page_number}}">
                        <img class="pagination__arrow" src="{% static 'img/arrow-left.svg' %}"> 
                        Atras
                    </a>
                </li>
            {% endif %}
            
            {% for pagina in paginator.page_range %}
                
            {% if pagina == page_obj.number %} 
            <li class="pagination-active"><span>{{pagina}}</span></li>
            {% else %}
            <li><a href="?page={{pagina}}" class="pagination-normal">{{ pagina }}</a></li>
            {% endif %}
    
            {% endfor %}
                
            {% if page_obj.has_next %}
            <li>
                <a href="?page={{page_obj.next_page_number}}">
                    Siguiente 
                    <img class="pagination__arrow" src="{% static 'img/arrow-right.svg' %}">
                </a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</div>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/store/categorias_productos.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %} Exonica Soliciones en Tecnología {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="categorias">
    <div class="categorias__listas">
        <ul class="categorias__lista">
            <li>
                <a href="?categoria={{categoria.all}}" class="categorias__link_all">Todas las categorias</a>
            </li>
            {% for categoria in categorias %}
            <li>
                <a href="?categoria={{categoria.short_name}}" class="categorias__link">{{categoria.name}}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <form class="categorias__form" method="GET">{% csrf_token %}
        <input class="categorias__input" type="text" id="kword" name="kword" placeholder="Buscar producto">
        <button class="categorias__btn" type="submit"> Buscar</button>
    </form>
    <div class="categorias__product">
        <section class="section section__categorias">
            <div class="section__container section__container--categorias">
                {% for art in articulos %}
                <div class="section__card section__card--categorias">
                    <div class="section__text">
                        <h1 class="section__card_text">{{art.title | truncatechars:21}}</h1>
                        <p class="section__price">${{art.precio|intcomma}}</p>
                    </div>
                    <picture>
                        <img src="{{ art.imagen.url }}" class="image" alt="{{art.title}}">
                    </picture>
                    <a href="{% url 'store_app:articulo_pub' art.slug %}" class="section__link">Ver</a>
                </div>
                {% empty %}
                <div class="uk-padding-small">
                    <h1 class="uk-heading-medium">No hay resultados</h1>
                </div>
                {% endfor %}
            </div>
        </section>

        <div class="paginated__admin">
            {% if is_paginated %}
            <ul>
                {% if page_obj.has_previous %}
                    <li><a href="?page={{page_obj.previous_page_number}}">
                            <img class="pagination__arrow" src="{% static 'img/arrow-left.svg' %}"> 
                            Atras
                        </a>
                    </li>
                {% endif %}
                
                {% for pagina in paginator.page_range %}
                    
                {% if pagina == page_obj.number %} 
                <li class="pagination-active"><span>{{pagina}}</span></li>
                {% else %}
                <li><a href="?page={{pagina}}" class="pagination-normal">{{ pagina }}</a></li>
                {% endif %}
        
                {% endfor %}
                    
                {% if page_obj.has_next %}
                <li>
                    <a href="?page={{page_obj.next_page_number}}">
                        Siguiente 
                        <img class="pagination__arrow" src="{% static 'img/arrow-right.svg' %}">
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>

{% include 'includes/footer.html' %}
{% endblock content %}

templates/store/detalle_articulo.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{articulos.title}} 
    {{articulos.descripcion}}
{% endblock title %}
{% block description %} 
    <meta name="description" content="{{articulos.descripcion}}">
{% endblock description %}
{% block content %}
{% include 'includes/header.html' %}


<section class="detail">
    <div class="detail__imagen">
        <picture class="detail__picture">
            <img src="{{ articulos.imagen.url }}" alt="{{articulos.title}}" class="detail__img">
        </picture>
    </div>
    <div class="detail__datos">
        <h1 class="detail__title">
            {{articulos.title}}
        </h1>
        <h3 class="detail__exo">
            {{articulos.categoria}}
        </h3>
        <p class="detail__articulo">
            {{articulos.descripcion}}
        </p>
        <h2 class="detail__sale">
            ${{articulos.precio}}
        </h2>
        <form action="{% url 'store_app:add_car_shop' articulos.id %}" method="POST" class="detail__form">{% csrf_token %}
            {% if user.estado == 'Sonora' %}
            <p>
                <input type="checkbox" name="instalacion" class="detail__check" id="id_instalacion">
                <label for="id_instalacion">Deseo contratar la instalación (+${{articulos.precio_inst}})</label>
            </p>
            {% else %}
            <p>
                <input type="checkbox" name="instalacion" class="detail__check" id="id_instalacion">
                <label for="id_instalacion">Deseo contratar la instalación (+${{articulos.precio_inst_fuera}})</label>
            </p>
            {% endif %}
            <div class="detail__div_sub">
                <p class="detail__cantidad">Cantidad:</p>
                <input type="number" name="count" value="1" class="form__one" min="1" required id="id_count">
                <button type="submit" class="section_new__link section_new__link--opacity section_new__link--modifer">Agregar al carrito</button>
            </div>
            
        </form>
    </div>
</section>
            
{% include 'includes/footer.html' %}
{% endblock content %}

templates/store/index.html
{% extends 'store/base_home.html' %}
{% load static %}
{% load humanize %}
{% block title %}
 Exonica Soluciones en Tecnología
{% endblock title %}

{% block description %} 
    <meta
        name="description" 
        content="
            {% for ab in aboutExo %}
                {{ ab.qsomos }}
            {% endfor %}
        "
    >
{% endblock description %}

{% block content %}
{% include 'includes/header.html' %}

{% if portada %}


    <div class="slider">
        <div class="slider__contenedor">
            {% for an in portada %}
            <section class="slider__contenido">
                <img src="{{ an.imagen.url }}" alt="{{an.title}}">
                <div>
                    <h1>{{an.title}}</h1>
                    <h2>{{an.mensaje}}</h2>
                </div>
            </section>
            {% endfor %}
        </div>
    </div>
{% endif %}

<div class="Carousel">
    <h2>LO NUEVO</h2>
    <div class="slick-list" id="slick-list">
        <button class="slick-arrow slick-prev" id="button-prev" data-button="button-prev" onclick="app.processingButton(event)">
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-left" class="svg-inline--fa fa-chevron-left fa-w-10" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M34.52 239.03L228.87 44.69c9.37-9.37 24.57-9.37 33.94 0l22.67 22.67c9.36 9.36 9.37 24.52.04 33.9L131.49 256l154.02 154.75c9.34 9.38 9.32 24.54-.04 33.9l-22.67 22.67c-9.37 9.37-24.57 9.37-33.94 0L34.52 272.97c-9.37-9.37-9.37-24.57 0-33.94z"></path></svg>
        </button>
        <div class="slick-track" id="track">
            {% for r in articulos_recientes %}
            <div class="slick">
                <picture>
                    <img src="{{ r.imagen.url }}" class="image__new" alt="{{r.title}}">
                </picture>
                <div class="section_new__text">
                    <h1 class="section_new__card_text">{{r.title}}</h1>
                    <p class="section_new__price">${{r.precio|intcomma}}</p>
                </div>
                <a href="{% url 'store_app:articulo_pub' r.slug %}" class="section_new__link section_new__link--opacity">Comprar</a>
            </div>
            {% endfor %}
        </div>
        <button class="slick-arrow slick-next" id="button-next" data-button="button-next" onclick="app.processingButton(event)">
            <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="chevron-right" class="svg-inline--fa fa-chevron-right fa-w-10" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"></path></svg>
        </button>
    </div>
</div>        

<section class="section">
    <h2>MAS PRODUCTOS</h2>
    <div class="section__container">
        {% for art in articulos_home %}
        <div class="section__card">
            <div class="section__text">
                <h1 class="section__card_text">{{art.title | truncatechars:21}}</h1>
                <p class="section__price">${{art.precio|intcomma}}</p>
            </div>
            <picture>
                <img src="{{ art.imagen.url }}" class="image" alt="{{art.title}}">
            </picture>
            <a href="{% url 'store_app:articulo_pub' art.slug %}" class="section__link">Ver</a>
        </div>
        {% endfor %}
    </div>
</section>

<section class="about" id="aboutus">
    <h2>SOBRE NOSOTROS</h2>
    <div class="about__container">
        <p>
            {% for ab in aboutExo %}
            {{ ab.qsomos }}
            {% endfor %}
        </p>
        
    </div>
    <section class="about__image">
    </section>
</section>


{% include 'includes/footer.html' %}
{% endblock content %}

templates/store/inform-contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Exonica Soluciones en Tecnología {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="contact">
    <figure class="contact__figure">
        <img src="{% static 'img/message-send.svg' %}" class="contact__img" alt="">
    </figure>
    <form action="{% url 'store_app:mensaje_contacto' %}" method="post" class="contact__form"> {% csrf_token %}
        <h1>Mandanos mensaje</h1>
        {{formContact.as_p}}
        <button class="section_new__link section_new__link--opacity contact__btn" type="submit">Enviar</button>    
    </form>
</div>
{% include 'includes/footer.html' %}
{% endblock content %}

templates/store/payment-trans.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %} Exonica Soluciones en Tecnología {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}


{% if productos %}
<div class="carshop carshop--transfer">
    <div class="payment__transfer-steps">
        <ul class="payment__transfer-text">
            <li>Deposita o transfiere la cantidad de ${{order | floatformat:2 | intcomma }} al siguiente número de cuenta Bancomer: <strong>0471447629</strong> a nombre de: <strong>Arleth Somail Gomez Galaviz</strong></li>
            <li>Toma una foto o captura de pantalla</li>
            <li>Da click en Seleccionar archivo y selecciona la imagen</li>
            <li>Da click en Comprar. Despues de verificar los datos prepararemos el envío a la dirección de tu perfil</li>
        </ul>
    </div>
    <p>Total: ${{order | floatformat:2 | intcomma }}</p>
    <form class="payment__form-transfer" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <label for="id_comprobante_pago">Comprobante de pago:</label>
        <input  type="file" name="comprobante_pago" accept="image/*" required id="id_comprobante_pago">
        <button type="submit" class="section_new__link section_new__link--opacity contact__payment">Comprar</button>
    </form>
        <table class="carshop__table table--payment">
            <thead>
                <tr>
                    <th></th>
                    <th>Producto</th>
                    <th>Precio</th>
                    <th>Cantidad</th>
                    <th>Instalación</th>
                    <th>Subtotal</th>
                </tr>
            </thead>
            <tbody>
                
                {% for p in productos %}
                <tr>
                    <td><img src="{{ p.product.imagen.url }}" style="height: 50px;"> </td>
                    <td>{{ p.product.title }}</td>
                    <td>${{ p.product.precio | floatformat:2 | intcomma }}</td>
                    <td>
                        {{ p.count }}
                    </td>

                    {% if p.instalacion == True %}
                        {% if p.user.estado == 'Sonora' %}
                            <td><p class="carshop__instalation">${{p.product.precio_inst | floatformat:2 | intcomma}}</p></td>
                        {% else %}
                            <td><p class="carshop__instalation">${{p.product.precio_inst_fuera | floatformat:2 | intcomma}}</p></td>
                        {% endif %}
                    {% else %}
                        <td><p class="carshop__instalation">No solicitada</p></td>
                    {% endif %}

                    <td>${{ p.subtotal }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
</div>
{% else %}
<br><br><br>
<div class="carshop__none-product">
    <h1 class="carshop__none_text">No tienes compras</h1>
    <img class="carshop__none_img" src="{% static 'img/cart-none.svg' %}" alt="">
</div>
{% endif %}


{% include 'includes/footer.html' %}
{% endblock content %}