applications/users/urls.py
from django.urls import path

from . import views

app_name = "user_app"

urlpatterns = [
    path(
        'userRegister', 
        views.UserRegisterView.as_view(), 
        name='Register'
    ),
    path(
        'userList', 
        views.UserListView.as_view(), 
        name='userList'
    ),
    path(
        'userEdit/<pk>/', 
        views.UserUpdateView.as_view(), 
        name='userEdit'
    ),
      path(
        'usuario-eliminar/<pk>/', 
        views.UserDeleteView.as_view(), 
        name='usuario_eliminar'
    ),
    path(
        'userLogin', 
        views.loginUser.as_view(), 
        name='login'
    ),
    path(
        'userLogout', 
        views.logoutUser.as_view(), 
        name='logout'
    ),
    path(
        'perfil-usuario', 
        views.UserPerfil.as_view(), 
        name='perfil_usuario'
    ),
    path(
        'editar-perfil-usuario', 
        views.UserUpdateForUser.as_view(), 
        name='editar_perfil_usuario'
    ),
]

exonica_online/urls.py
from unicodedata import name
from django.contrib import admin
from django.urls import path, re_path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from applications.store_exonica.sitemap import (
    Sitemap,
    articulosSitem
)
urlpatterns_main = [
    path('admin/', admin.site.urls),
    re_path('', include('applications.admin_exonica.urls')),
    re_path('', include('applications.store_exonica.urls')),
    re_path('', include('applications.users.urls')),
    # Url Ckeditor
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitemaps = {
    'site':Sitemap(
        [
            'store_app:pub_articulos'
        ]
    ),
    'articulos': articulosSitem
}

urlpatterns_sitemap = [
    path(
        'sitemap.xml',
        sitemap, 
        {'sitemaps':sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    )
]


urlpatterns = urlpatterns_main + urlpatterns_sitemap

applications/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .managers import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    ADMINISTRADOR = 'Administrador'
    CLIENTE = 'Cliente'

    HOMBRE = 'Masculino'
    MUJER = 'Femenino'

    AGUAS_CALIENTE = 'Aguascalientes'
    BAJA_CALIFORNIA = 'Baja California'
    BAJA_CALIFORNIA_SUR = 'Baja California Sur'
    CAMPECHE = 'Campeche'
    CHIAPAS = 'Chiapas'
    CHIHUAHUA = 'Chihuahua'
    COAHUILA = 'Coahuila'
    COLIMA = 'Colima'
    DURANGO = 'Durango'
    GUANAJUATO = 'Guanajuato'
    GUERRERO = 'Guerrero'
    HIDALGO = 'Hidalgo'
    JALISCO = 'Jalisco'
    EDO_MEXICO = 'Estado de México'
    MICHOACAN = 'Michoacán'
    MORELOS = 'Morelos'
    NAYARIT = 'Nayarit'
    NUEVO_LEON = 'Nuevo León'
    OAXACA = 'Oaxaca'
    PUEBLA = 'Puebla'
    QUERETARO = 'Querétaro'
    QUINTANA_ROO = 'Quintana Roo'
    SAN_LUIS_PTSI = 'San Luis Potosí'
    SINALOA = 'Sinaloa'
    SONORA = 'Sonora'
    TABASCO = 'Tabasco'
    TAMAULIPAS = 'Tamaulipas'
    TLAXCALA = 'Tlaxcala'
    VERACRUZ = 'Veracruz'
    YUCATAN = 'Yucatán'
    ZACATECAS = 'Zacatecas'



    OCUPATION_CHOICES = [
        (ADMINISTRADOR, 'Administrador'),
        (CLIENTE, 'Cliente'),
    ]


    GENERO_CHOICES = [
        (HOMBRE, 'Masculino'),
        (MUJER, 'Femenino'),
    ]
        
    

    STATE_CHOICES = [
        (AGUAS_CALIENTE, 'Aguascalientes'),
        (BAJA_CALIFORNIA, 'Baja California'),
        (BAJA_CALIFORNIA_SUR, 'Baja California Sur'),
        (CAMPECHE, 'Campeche'),
        (CHIAPAS, 'Chiapas'),
        (CHIHUAHUA, 'Chihuahua'),
        (COAHUILA, 'Coahuila'),
        (COLIMA, 'Colima'),
        (DURANGO, 'Durango'),
        (GUANAJUATO, 'Guanajuato'),
        (GUERRERO, 'Guerrero'),
        (HIDALGO, 'Hidalgo'),
        (JALISCO, 'Jalisco'),
        (EDO_MEXICO, 'Estado de México'),
        (MICHOACAN, 'Michoacán'),
        (MORELOS, 'Morelos'),
        (NAYARIT, 'Nayarit'),
        (NUEVO_LEON, 'Nuevo León'),
        (OAXACA, 'Oaxaca'),
        (PUEBLA, 'Puebla'),
        (QUERETARO, 'Querétaro'),
        (QUINTANA_ROO, 'Quintana Roo'),
        (SAN_LUIS_PTSI, 'San Luis Potosí'),
        (SINALOA, 'Sinaloa'),
        (SONORA, 'Sonora'),
        (TABASCO, 'Tabasco'),
        (TAMAULIPAS, 'Tamaulipas'),
        (TLAXCALA, 'Tlaxcala'),
        (VERACRUZ, 'Veracruz'),
        (YUCATAN, 'Yucatán'),
        (ZACATECAS, 'Zacatecas')
    ]

    nombre = models.CharField(max_length=20, blank=False)
    apellidos = models.CharField(max_length=50, blank=False)
    fecha_nacimiento = models.DateField(
        'Fecha de nacimiento', 
        blank=True,
        null=True
    )
    email = models.EmailField(unique=True)
    celular = models.CharField(max_length=10)
    genero = models.CharField(max_length=10, choices=GENERO_CHOICES)
    ciudad = models.CharField(max_length=20)
    estado = models.CharField(max_length=20, choices=STATE_CHOICES)
    direccion_envio = models.CharField('Direccion de envío', max_length=100)
    cpostal = models.CharField('Codigo Postal', max_length=6)
    ocupations = models.CharField(max_length=15, choices=OCUPATION_CHOICES, default=CLIENTE)

    # administrador o no
    is_staff = models.BooleanField(default=False)
    # super usuario o no
    is_superuser = models.BooleanField('Super Usuario', default=False)
    
    USERNAME_FIELD = 'email'

    objects = UserManager()

    def get_short_name(self):
        return self.nombre
    def get_full_name(self):
        return self.nombre + ' ' + self.apellidos

applications/users/forms.py
from django.contrib.auth import authenticate
from django import forms
from .models import User

class UserRegisterForm(forms.ModelForm):

    password_1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form__two',
                'placeholder': 'Contraseña'
            }
        )
    )
    password_2 = forms.CharField(
        label='Confirmar contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'class': 'form__two',
                'placeholder': 'Repetir Contraseña'
            }
        )
    )

    class Meta:
        model = User
        fields = (
            'nombre',
            'apellidos',
            'fecha_nacimiento',
            'email',
            'celular',
            'genero',
            'ciudad',
            'estado',
            'direccion_envio',
            'cpostal'
        )
        widgets = {
            'nombre': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'apellidos': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'fecha_nacimiento': forms.DateInput(
                format='%Y-%m-%d',
                attrs= {
                    'type': 'date',
                    'class': 'form__two',
                }
            ),
            'email': forms.EmailInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'celular': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'genero': forms.Select(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'ciudad': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'estado': forms.Select(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'direccion_envio': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'cpostal': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
        }

    def clean_password_2(self):
        if self.cleaned_data['password_2'] != self.cleaned_data['password_1']:
            self.add_error('password_2', 'Las contraseñas no coinciden')
        elif len(self.cleaned_data['password_1']) < 5:
            self.add_error('password_1', 'La contraseña no debe ser menor a 5 digitos')
        

class UserLoginForm(forms.Form):

    email = forms.EmailField(
        required=True,
    )

    password = forms.CharField(
        label=False,
    )

    def clean(self):
        cleaned_data = super(UserLoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError('Correo y/o contraseña incorrectos')

        return self.cleaned_data


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'ocupations',
            'is_superuser',
        )
        widgets = {
            'ocupations': forms.Select(
                attrs= {
                    'class': 'form__two',
                    
                }
            ),
            'is_superuser': forms.CheckboxInput(
                attrs= {
                    'class': 'detail__check',
                }
            ),
        }

class UserUpdatePerfilForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'nombre',
            'apellidos',
            'fecha_nacimiento',
            'email',
            'celular',
            'genero',
            'ciudad',
            'estado',
            'direccion_envio',
            'cpostal'
        )
        widgets = {
            'nombre': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'apellidos': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'fecha_nacimiento': forms.DateInput(
                format='%Y-%m-%d',
                attrs= {
                    'type': 'date',
                    'class': 'form__two',
                }
            ),
            'email': forms.EmailInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'celular': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'genero': forms.Select(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'ciudad': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'estado': forms.Select(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'direccion_envio': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
            'cpostal': forms.TextInput(
                attrs= {
                    'class': 'form__two',
                }
            ),
        }

applications/users/views.py
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.views.generic import (
    View,
    ListView,
    UpdateView,
    DeleteView
)
from django.views.generic.base import TemplateView, View
from django.views.generic.edit import FormView
from .forms import UserRegisterForm, UserLoginForm, UserUpdateForm, UserUpdatePerfilForm
from .models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from applications.users.mixin import AdminPermisoMixin


class UserRegisterView(FormView):
    template_name = "users/registerUser.html"
    form_class = UserRegisterForm
    success_url = reverse_lazy('user_app:login')
    
    def form_valid(self, form):
        User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password_1'],
            ## ExtraFields
            nombre = form.cleaned_data['nombre'],
            apellidos = form.cleaned_data['apellidos'],
            fecha_nacimiento = form.cleaned_data['fecha_nacimiento'],
            celular = form.cleaned_data['celular'],
            genero = form.cleaned_data['genero'],
            ciudad = form.cleaned_data['ciudad'],
            estado = form.cleaned_data['estado'],
            direccion_envio = form.cleaned_data['direccion_envio']
        )
        return super(UserRegisterView, self).form_valid(form)


class loginUser(FormView):
    template_name = "users/loginUser.html"
    form_class = UserLoginForm
    success_url = reverse_lazy('store_app:pub_articulos')

    def form_valid(self, form):
        email = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, email)
        return super(loginUser, self).form_valid(form)

class logoutUser(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'store_app:pub_articulos'
            )
        )


class UserListView(AdminPermisoMixin, LoginRequiredMixin, ListView):
    model = User
    template_name = "admin/list_user.html"
    context_object_name = 'listarusuarios'
    paginate_by = '5'
    ordering = 'nombre'
    login_url = reverse_lazy('user_app:login')
    permission_required = 'applications.admin_exonica'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = "admin/editar_usuario.html"
    form_class = UserUpdateForm
    success_url = reverse_lazy('user_app:userList')
    login_url = reverse_lazy('user_app:login')
    permission_required = 'applications.admin_exonica'


class UserDeleteView(DeleteView):
    model = User
    template_name = "admin/eliminar_usuario.html"
    context_object_name = 'usuariodelete'
    success_url = reverse_lazy('user_app:userList')
    permission_required = 'applications.admin_exonica'

class UserUpdateForUser(LoginRequiredMixin, UpdateView):
    model = User
    template_name = "users/editar_perfil.html"
    form_class = UserUpdatePerfilForm
    success_url = reverse_lazy('user_app:perfil_usuario')
    login_url = reverse_lazy('user_app:login')


    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def get_object(self):
        return self.request.user


class UserPerfil(LoginRequiredMixin, TemplateView):
    template_name = "users/mi_perfil.html"
    login_url = reverse_lazy('user_app:login')


    def get_context_data(self, **kwargs):
        context = super(UserPerfil, self).get_context_data(**kwargs)
        # Contexto de portada
        context["miPerfil"] = self.request.user
        return context

templates/users/editar_perfil.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Exonica Soluciones en Tecnología {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="perfil__editar">
    <picture class="editar__img">
        <img src="{% static 'img/editar_img.svg' %}" class="editar__image">
    </picture>
    <h1>Editar mi perfil</h1>
    <form class="editar__form" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="editar__container_one">   
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre }}
            <label for="id_apellidos">Apellidos:</label>
            {{ form.apellidos }}
            <label for="id_fecha_nacimiento">Fecha de nacimiento:</label>
            {{ form.fecha_nacimiento }}
            <label for="id_email">Email:</label>
            {{ form.email }} 
            <label for="id_celular">Celular:</label>
            {{ form.celular }} 
        </div>
        <div class="editar__container_two">
            <label for="id_genero">Genero:</label>
            {{ form.genero }} 
            <label for="id_ciudad">Ciudad:</label>
            {{ form.ciudad }} 
            <label for="id_estado">Estado:</label>
            {{ form.estado }} 
            <label for="id_direccion_envio">Dirección de envío:</label>
            {{ form.direccion_envio }} 
            <label for="id_cpostal">Codigo Postal:</label>
            {{ form.cpostal }} 
        </div>
        <button class="perfil__btn" type="submit">Modificar</button>
    </form>
</div>
    
{% include 'includes/footer.html' %}
{% endblock content %}

templates/users/loginUser.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Exonica Soluciones en Tecnología {% endblock title %}
{% block content %}
<div class="login">
	<figure class="login__figure">
		<img src="{% static 'img/login.svg' %}" class="login__img" alt="">
	</figure>
	<form class="login__form" method="post">{% csrf_token %}
		<div class="login__cabecera">
			<img src="{% static 'img/exologo.png' %}" class="login__logo" alt="">
			<h1>EXONICA</h1>
			<h3>Soluciones en tecnologia</h3>
		</div>
		<p> 
			<div class="form__login_group">
				<input type="email" name="email" class="login__inputs" placeholder=" " required id="id_email">
				<label class="login__label">Email: </label>
			</div>
		</p>
		<p> 
			<div class="form__login_group">
				<input type="password" name="password" class="login__inputs" placeholder=" " required id="id_password">
				<label class="login__label">Password: </label>
			</div>
		</p>
		<button type="submit" class="section_new__link section_new__link--opacity contact__btn">Iniciar sesión</button>
		<a href="{% url 'user_app:Register' %}" class="register_link">Registrarse</a>
	</form>
</div>
{% endblock content %}

templates/users/mi_perfil.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %} Exonica Soluciones en Tecnología {% endblock title %}
{% block content %}
{% include 'includes/header.html' %}

<div class="perfil">
    <picture class="perfil__avatar">
        <h1>Mi perfil</h1>
        {% if user.genero == 'Masculino' %}
        <img src="{% static 'img/male_avatar.svg' %}" class="perfil__img">
        {% else %}
        <img src="{% static 'img/female_avatar.svg' %}" class="perfil__img">
        {% endif %}
    </picture>
    <a href="{% url 'user_app:editar_perfil_usuario' %}" class="perfil__edit">Editar datos de mi perfil</a>
    <div class="perfil__container_one">   
        <div class="perfil__datos_one">
            <h3>Nombre</h3>
            <p>{{miPerfil.nombre}}</p>
        </div>
        <div class="perfil__datos_one">
            <h3>Apellidos</h3>
            <p>{{miPerfil.apellidos}}</p>
        </div>
        <div class="perfil__datos_one">
            <h3>Fecha de nacimiento</h3>
            <p>{{miPerfil.fecha_nacimiento}}</p>
        </div>
        <div class="perfil__datos_one">
            <h3>Email</h3>
            <p>{{miPerfil.email}}</p>
        </div>
        <div class="perfil__datos_one">
            <h3>Celular</h3>
            <p>{{miPerfil.celular}}</p>
        </div>
    </div>
    <div class="perfil__container_two">
        <div class="perfil__datos_two">
            <h3>Genero</h3>
            <p>{{miPerfil.genero}}</p>
        </div>
        <div class="perfil__datos_two">
            <h3>Ciudad</h3>
            <p>{{miPerfil.ciudad}}</p>
        </div>
        <div class="perfil__datos_two">
            <h3>Estado</h3>
            <p>{{miPerfil.estado}}</p>
        </div>
        <div class="perfil__datos_two">
            <h3>Dirección de envío</h3>
            <p>{{miPerfil.direccion_envio}}</p>
        </div>
        <div class="perfil__datos_two">
            <h3>Codigo Postal</h3>
            <p>{{miPerfil.cpostal}}</p>
        </div>
    </div>
</div>


{% include 'includes/footer.html' %}
{% endblock content %}

templates/users/registerUser.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Exonica Soluciones en Tecnología {% endblock title %}
{% block content %}

<div class="register">
	<figure class="register__figure">
		<img src="{% static 'img/register-ilust.svg' %}" class="register__img" alt="">
	</figure>
	<form class="register__form" method="post">{% csrf_token %}
		<div class="login__cabecera">
			<img src="{% static 'img/exologo.png' %}" class="register__logo" alt="">
			<h1>EXONICA</h1>
			<h3>Soluciones en tecnologia</h3>
		</div>
		<a href="{% url 'user_app:login' %}" class="register_link">Ir a inicio de sesión</a>
		{{form.as_p}}
		<button type="submit" class="section_new__link section_new__link--opacity contact__btn">Registrarse</button>

	</form>
</div>
{% endblock content %}